const pool = require('../config/db');
const id = (v) => Number.isInteger(Number(v)) && Number(v) > 0;
const title = (v) => typeof v === 'string' && v.trim() && v.trim().length <= 255;
async function board(connection, boardId, userId) {
  const [b] = await connection.query('SELECT * FROM boards WHERE id=? AND user_id=?', [boardId, userId]);
  if (!b.length) return null;
  const [cols] = await connection.query('SELECT * FROM columns WHERE board_id=? ORDER BY position,id', [boardId]);
  const [tasks] = await connection.query('SELECT t.* FROM tasks t JOIN columns c ON c.id=t.column_id WHERE c.board_id=? ORDER BY t.position,t.id', [boardId]);
  const [subs] = await connection.query('SELECT s.* FROM subtasks s JOIN tasks t ON t.id=s.task_id JOIN columns c ON c.id=t.column_id WHERE c.board_id=? ORDER BY s.id', [boardId]);
  return { ...b[0], columns: cols.map(c => ({ ...c, tasks: tasks.filter(t => t.column_id === c.id).map(t => ({ ...t, subtasks: subs.filter(s => s.task_id === t.id).map(s => ({ ...s, is_completed: Boolean(s.is_completed) })) })) })) };
}
exports.getBoards = async (req, res) => { try { const [rows] = await pool.query('SELECT * FROM boards WHERE user_id=? ORDER BY created_at DESC', [req.user.id]); return res.json(rows); } catch (e) { console.error(e); return res.status(500).json({ message: 'დაფების წამოღება ვერ მოხერხდა' }); } };
exports.getBoardById = async (req, res) => { if (!id(req.params.id)) return res.status(400).json({ message: 'არასწორი დაფის ID' }); try { const b = await board(pool, req.params.id, req.user.id); return b ? res.json(b) : res.status(404).json({ message: 'დაფა ვერ მოიძებნა ან წვდომა აკრძალულია' }); } catch (e) { console.error(e); return res.status(500).json({ message: 'დაფის სტრუქტურის წამოღება ვერ მოხერხდა' }); } };
exports.createBoard = async (req, res) => {
  if (!title(req.body.title) || (req.body.columns !== undefined && !Array.isArray(req.body.columns))) return res.status(400).json({ message: 'სწორი title და columns აუცილებელია' });
  const cols = req.body.columns || []; if (cols.some(c => !title(typeof c === 'string' ? c : c && c.title))) return res.status(400).json({ message: 'სვეტის სათაური არასწორია' });
  const c = await pool.getConnection(); try { await c.beginTransaction(); const [r] = await c.query('INSERT INTO boards (user_id,title) VALUES (?,?)', [req.user.id, req.body.title.trim()]);
    for (let i=0;i<cols.length;i++) await c.query('INSERT INTO columns (board_id,title,position) VALUES (?,?,?)', [r.insertId, (typeof cols[i] === 'string' ? cols[i] : cols[i].title).trim(), i]);
    const result = await board(c, r.insertId, req.user.id); await c.commit(); return res.status(201).json(result);
  } catch(e) { await c.rollback(); console.error(e); return res.status(500).json({ message: 'დაფის შექმნა ვერ მოხერხდა' }); } finally { c.release(); }
};
exports.addColumn = async (req, res) => { if (!id(req.params.boardId) || !title(req.body.title)) return res.status(400).json({ message: 'სწორი boardId და title აუცილებელია' }); const c=await pool.getConnection(); try { await c.beginTransaction(); const [b]=await c.query('SELECT id FROM boards WHERE id=? AND user_id=? FOR UPDATE',[req.params.boardId,req.user.id]); if(!b.length){await c.rollback();return res.status(404).json({message:'დაფა ვერ მოიძებნა ან წვდომა აკრძალულია'});} const [n]=await c.query('SELECT COALESCE(MAX(position)+1,0) position FROM columns WHERE board_id=?',[req.params.boardId]); const [r]=await c.query('INSERT INTO columns (board_id,title,position) VALUES (?,?,?)',[req.params.boardId,req.body.title.trim(),n[0].position]); await c.commit(); return res.status(201).json({id:r.insertId,board_id:Number(req.params.boardId),title:req.body.title.trim(),position:n[0].position,tasks:[]}); }catch(e){await c.rollback();console.error(e);return res.status(500).json({message:'სვეტის დამატება ვერ მოხერხდა'});}finally{c.release();} };
exports.updateBoard = async (req, res) => {
  if (!id(req.params.id) || (req.body.title !== undefined && !title(req.body.title)) || (req.body.columns !== undefined && !Array.isArray(req.body.columns))) return res.status(400).json({message:'მონაცემები არასწორია'});
  const c=await pool.getConnection(); try { await c.beginTransaction(); const [b]=await c.query('SELECT id FROM boards WHERE id=? AND user_id=? FOR UPDATE',[req.params.id,req.user.id]); if(!b.length){await c.rollback();return res.status(404).json({message:'დაფა ვერ მოიძებნა ან წვდომა აკრძალულია'});} if(req.body.title!==undefined) await c.query('UPDATE boards SET title=? WHERE id=?',[req.body.title.trim(),req.params.id]);
    if(req.body.columns!==undefined){const [existing]=await c.query('SELECT id FROM columns WHERE board_id=?',[req.params.id]); const incoming=req.body.columns; if(incoming.some(x=>!title(x&&x.title))||incoming.some(x=>x.id!==undefined&&!id(x.id))){await c.rollback();return res.status(400).json({message:'სვეტები არასწორია'});} const keep=incoming.filter(x=>x.id).map(x=>Number(x.id)); if(keep.length!==new Set(keep).size){await c.rollback();return res.status(400).json({message:'დუბლირებული სვეტი'});} for(const x of existing) if(!keep.includes(x.id)) await c.query('DELETE FROM columns WHERE id=? AND board_id=?',[x.id,req.params.id]); for(let i=0;i<incoming.length;i++){const x=incoming[i]; if(x.id){const [ok]=await c.query('SELECT id FROM columns WHERE id=? AND board_id=?',[x.id,req.params.id]); if(!ok.length){await c.rollback();return res.status(400).json({message:'სვეტი ამ დაფას არ ეკუთვნის'});} await c.query('UPDATE columns SET title=?,position=? WHERE id=?',[x.title.trim(),i,x.id]);}else await c.query('INSERT INTO columns (board_id,title,position) VALUES (?,?,?)',[req.params.id,x.title.trim(),i]);}}
    const result=await board(c,req.params.id,req.user.id); await c.commit(); return res.json(result);
  }catch(e){await c.rollback();console.error(e);return res.status(500).json({message:'დაფის განახლება ვერ მოხერხდა'});}finally{c.release();}
};
exports.deleteBoard = async (req,res)=>{if(!id(req.params.id))return res.status(400).json({message:'არასწორი ID'});try{const [r]=await pool.query('DELETE FROM boards WHERE id=? AND user_id=?',[req.params.id,req.user.id]);return r.affectedRows?res.json({message:'დაფა წარმატებით წაიშალა'}):res.status(404).json({message:'დაფა ვერ მოიძებნა ან წვდომა აკრძალულია'});}catch(e){console.error(e);return res.status(500).json({message:'დაფის წაშლა ვერ მოხერხდა'});}};
